apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
stringData:
  # 👇 Adicionado o ".default.svc.cluster.local" após o nome do banco
  DATABASE_URL: "postgresql://postgres:OficinaFiap2026!@oficina-db-prod.ctomhztfsbks.us-east-1.rds.amazonaws.com:5432/postgres"
  JWT_SECRET: "seu-segredo-super-seguro-aqui"